services:
  api:
    build:
      context: .
    environment:
      - ADDRESS=0.0.0.0:3000
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus

